bot:
  # Токен бота, можно получить у @BotFather
  token: "7640569667:AAGrTuTHmlJbOu8ZlvJ4AfLXR0d1fHUjqsU"

db:
  # Строка подключения к базе данных.
  # Ниже заполненный пример, если используете Docker Compose файл из каталога
  dsn: "postgresql+psycopg://superuser:superpassword@127.0.0.1/data"
  # Если указать "yes", то при создании движка параметр "echo" будет True,
  # что приведёт к выводу на экран расширенной информации о взаимодействии
  # SQLAlchemy и базы данных. В противном случае укажите "no"
  is_echo: "yes"